# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'HistoriaClinica'
        db.create_table('ActividadesClinicas_historiaclinica', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('paciente', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['altas.Paciente'])),
            ('medico', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['altas.Medico'])),
            ('ultimaVisitaMedica', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, blank=True)),
            ('herenciaPatologicaopciones', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('herenciaMadre', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('herenciaPadre', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('herenciaHermanos', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('herenciaHijos', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('herenciaEsposos', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('herenciaTios', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('herenciaAbuelos', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('eInflamatoriasnotopciones', self.gf('django.db.models.fields.TextField')()),
            ('ets', self.gf('django.db.models.fields.TextField')()),
            ('eDegenerativas', self.gf('django.db.models.fields.TextField')()),
            ('eNeoplasticas', self.gf('django.db.models.fields.TextField')()),
            ('eCongenitas', self.gf('django.db.models.fields.TextField')()),
            ('otras', self.gf('django.db.models.fields.TextField')()),
            ('habitosHigienicosVest', self.gf('django.db.models.fields.TextField')()),
            ('habitosHigienicosCorp', self.gf('django.db.models.fields.TextField')()),
            ('frecuenciaLavadoDental', self.gf('django.db.models.fields.TextField')()),
            ('uxiliaresBucales', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('consumodeGolosinas', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('gruposanguineo', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('factorRh', self.gf('django.db.models.fields.CharField')(max_length=5)),
            ('cartilladeVacunacion', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('esquemaCompleto', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('esquemaFalta', self.gf('django.db.models.fields.CharField')(max_length=200)),
            ('adicciones', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('alergias', self.gf('django.db.models.fields.CharField')(max_length=400)),
            ('fechaHospitalizaion', self.gf('django.db.models.fields.DateTimeField')()),
            ('motivo', self.gf('django.db.models.fields.CharField')(max_length=400)),
            ('padecimientoActual', self.gf('django.db.models.fields.CharField')(max_length=200)),
            ('aparatoDigestivo', self.gf('django.db.models.fields.TextField')()),
            ('aparatoRespiratorio', self.gf('django.db.models.fields.TextField')()),
            ('aparatoCardioBascular', self.gf('django.db.models.fields.TextField')()),
            ('apararoGenitourinario', self.gf('django.db.models.fields.TextField')()),
            ('sistemaHemopoyetico', self.gf('django.db.models.fields.TextField')()),
            ('sistemamusculoEsqueletico', self.gf('django.db.models.fields.TextField')()),
            ('aparatoTegumentario', self.gf('django.db.models.fields.TextField')()),
            ('habitusExterior', self.gf('django.db.models.fields.TextField')()),
            ('peso', self.gf('django.db.models.fields.CharField')(max_length=5)),
            ('talla', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('complexion', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('frecuenciaCardiaca', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('tensionarterial', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('frecuenciaRespiratoria', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('temperatura', self.gf('django.db.models.fields.CharField')(max_length=60)),
            ('cabeza', self.gf('django.db.models.fields.CharField')(max_length=400)),
            ('craneo', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('caraAsimetria', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('perfil', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('piel', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('musculos', self.gf('django.db.models.fields.CharField')(max_length=500)),
            ('cuello', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('otros', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('ruidos', self.gf('django.db.models.fields.CharField')(max_length=35)),
            ('chasquidos', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('crepitacion', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('difparaAbrirlaboca', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('dolorabertura', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('fatigadolormuscular', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('disminuciondelaavertura', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('desviacionaverturadecierre', self.gf('django.db.models.fields.CharField')(max_length=10)),
            ('ganglios', self.gf('django.db.models.fields.TextField')()),
            ('glandulassalivales', self.gf('django.db.models.fields.TextField')()),
            ('labioExterno', self.gf('django.db.models.fields.TextField')()),
            ('bordebermellon', self.gf('django.db.models.fields.TextField')()),
            ('labiointerno', self.gf('django.db.models.fields.TextField')()),
            ('Comisuras', self.gf('django.db.models.fields.TextField')()),
            ('carrillos', self.gf('django.db.models.fields.TextField')()),
            ('fondodesaco', self.gf('django.db.models.fields.TextField')()),
            ('frenillos', self.gf('django.db.models.fields.TextField')()),
            ('lenguaTerciomedio', self.gf('django.db.models.fields.TextField')()),
            ('paladarDuro', self.gf('django.db.models.fields.TextField')()),
            ('paladarBlando', self.gf('django.db.models.fields.TextField')()),
            ('istmoBucofaringe', self.gf('django.db.models.fields.TextField')()),
            ('lenguaDorso', self.gf('django.db.models.fields.TextField')()),
            ('lenguaBordes', self.gf('django.db.models.fields.TextField')()),
            ('lenguaVentral', self.gf('django.db.models.fields.TextField')()),
            ('pisodelaBoca', self.gf('django.db.models.fields.TextField')()),
            ('dientes', self.gf('django.db.models.fields.TextField')()),
            ('mucosadelBordealveolar', self.gf('django.db.models.fields.TextField')()),
            ('encia', self.gf('django.db.models.fields.TextField')()),
            ('sistemaEndocrina', self.gf('django.db.models.fields.TextField')()),
            ('gingivitis', self.gf('django.db.models.fields.TextField')()),
            ('periodontitis', self.gf('django.db.models.fields.TextField')()),
            ('receciongingival', self.gf('django.db.models.fields.TextField')()),
            ('bolsasperiodontales', self.gf('django.db.models.fields.TextField')()),
            ('movilidadDentario', self.gf('django.db.models.fields.TextField')()),
            ('indicedeplaca', self.gf('django.db.models.fields.TextField')()),
            ('interpretacionradiografica', self.gf('django.db.models.fields.TextField')()),
            ('estudiosdeLaboratorio', self.gf('django.db.models.fields.TextField')()),
            ('interpretacionEstudiosLaboratorio', self.gf('django.db.models.fields.TextField')()),
        ))
        db.send_create_signal('ActividadesClinicas', ['HistoriaClinica'])

        # Adding model 'ListadeDiagnosticos'
        db.create_table('ActividadesClinicas_listadediagnosticos', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('codigoDiagnostico', self.gf('django.db.models.fields.CharField')(max_length=15)),
            ('nombreDiagnostico', self.gf('django.db.models.fields.CharField')(max_length=30)),
        ))
        db.send_create_signal('ActividadesClinicas', ['ListadeDiagnosticos'])

        # Adding model 'Odontograma'
        db.create_table('ActividadesClinicas_odontograma', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('doctor', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['altas.Medico'])),
            ('paciente', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['altas.Paciente'])),
            ('fechayHora', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, blank=True)),
            ('nombrePiezaDental', self.gf('django.db.models.fields.CharField')(max_length=40)),
            ('problemaDental', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['ActividadesClinicas.ListadeDiagnosticos'])),
            ('notas', self.gf('django.db.models.fields.TextField')()),
        ))
        db.send_create_signal('ActividadesClinicas', ['Odontograma'])


    def backwards(self, orm):
        # Deleting model 'HistoriaClinica'
        db.delete_table('ActividadesClinicas_historiaclinica')

        # Deleting model 'ListadeDiagnosticos'
        db.delete_table('ActividadesClinicas_listadediagnosticos')

        # Deleting model 'Odontograma'
        db.delete_table('ActividadesClinicas_odontograma')


    models = {
        'ActividadesClinicas.historiaclinica': {
            'Comisuras': ('django.db.models.fields.TextField', [], {}),
            'Meta': {'object_name': 'HistoriaClinica'},
            'adicciones': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'alergias': ('django.db.models.fields.CharField', [], {'max_length': '400'}),
            'apararoGenitourinario': ('django.db.models.fields.TextField', [], {}),
            'aparatoCardioBascular': ('django.db.models.fields.TextField', [], {}),
            'aparatoDigestivo': ('django.db.models.fields.TextField', [], {}),
            'aparatoRespiratorio': ('django.db.models.fields.TextField', [], {}),
            'aparatoTegumentario': ('django.db.models.fields.TextField', [], {}),
            'bolsasperiodontales': ('django.db.models.fields.TextField', [], {}),
            'bordebermellon': ('django.db.models.fields.TextField', [], {}),
            'cabeza': ('django.db.models.fields.CharField', [], {'max_length': '400'}),
            'caraAsimetria': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'carrillos': ('django.db.models.fields.TextField', [], {}),
            'cartilladeVacunacion': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'chasquidos': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'complexion': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'consumodeGolosinas': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'craneo': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'crepitacion': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'cuello': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'desviacionaverturadecierre': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'dientes': ('django.db.models.fields.TextField', [], {}),
            'difparaAbrirlaboca': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'disminuciondelaavertura': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'dolorabertura': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'eCongenitas': ('django.db.models.fields.TextField', [], {}),
            'eDegenerativas': ('django.db.models.fields.TextField', [], {}),
            'eInflamatoriasnotopciones': ('django.db.models.fields.TextField', [], {}),
            'eNeoplasticas': ('django.db.models.fields.TextField', [], {}),
            'encia': ('django.db.models.fields.TextField', [], {}),
            'esquemaCompleto': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'esquemaFalta': ('django.db.models.fields.CharField', [], {'max_length': '200'}),
            'estudiosdeLaboratorio': ('django.db.models.fields.TextField', [], {}),
            'ets': ('django.db.models.fields.TextField', [], {}),
            'factorRh': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'fatigadolormuscular': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'fechaHospitalizaion': ('django.db.models.fields.DateTimeField', [], {}),
            'fondodesaco': ('django.db.models.fields.TextField', [], {}),
            'frecuenciaCardiaca': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'frecuenciaLavadoDental': ('django.db.models.fields.TextField', [], {}),
            'frecuenciaRespiratoria': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'frenillos': ('django.db.models.fields.TextField', [], {}),
            'ganglios': ('django.db.models.fields.TextField', [], {}),
            'gingivitis': ('django.db.models.fields.TextField', [], {}),
            'glandulassalivales': ('django.db.models.fields.TextField', [], {}),
            'gruposanguineo': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'habitosHigienicosCorp': ('django.db.models.fields.TextField', [], {}),
            'habitosHigienicosVest': ('django.db.models.fields.TextField', [], {}),
            'habitusExterior': ('django.db.models.fields.TextField', [], {}),
            'herenciaAbuelos': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'herenciaEsposos': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'herenciaHermanos': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'herenciaHijos': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'herenciaMadre': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'herenciaPadre': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'herenciaPatologicaopciones': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'herenciaTios': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'indicedeplaca': ('django.db.models.fields.TextField', [], {}),
            'interpretacionEstudiosLaboratorio': ('django.db.models.fields.TextField', [], {}),
            'interpretacionradiografica': ('django.db.models.fields.TextField', [], {}),
            'istmoBucofaringe': ('django.db.models.fields.TextField', [], {}),
            'labioExterno': ('django.db.models.fields.TextField', [], {}),
            'labiointerno': ('django.db.models.fields.TextField', [], {}),
            'lenguaBordes': ('django.db.models.fields.TextField', [], {}),
            'lenguaDorso': ('django.db.models.fields.TextField', [], {}),
            'lenguaTerciomedio': ('django.db.models.fields.TextField', [], {}),
            'lenguaVentral': ('django.db.models.fields.TextField', [], {}),
            'medico': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['altas.Medico']"}),
            'motivo': ('django.db.models.fields.CharField', [], {'max_length': '400'}),
            'movilidadDentario': ('django.db.models.fields.TextField', [], {}),
            'mucosadelBordealveolar': ('django.db.models.fields.TextField', [], {}),
            'musculos': ('django.db.models.fields.CharField', [], {'max_length': '500'}),
            'otras': ('django.db.models.fields.TextField', [], {}),
            'otros': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'paciente': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['altas.Paciente']"}),
            'padecimientoActual': ('django.db.models.fields.CharField', [], {'max_length': '200'}),
            'paladarBlando': ('django.db.models.fields.TextField', [], {}),
            'paladarDuro': ('django.db.models.fields.TextField', [], {}),
            'perfil': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'periodontitis': ('django.db.models.fields.TextField', [], {}),
            'peso': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'piel': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'pisodelaBoca': ('django.db.models.fields.TextField', [], {}),
            'receciongingival': ('django.db.models.fields.TextField', [], {}),
            'ruidos': ('django.db.models.fields.CharField', [], {'max_length': '35'}),
            'sistemaEndocrina': ('django.db.models.fields.TextField', [], {}),
            'sistemaHemopoyetico': ('django.db.models.fields.TextField', [], {}),
            'sistemamusculoEsqueletico': ('django.db.models.fields.TextField', [], {}),
            'talla': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'temperatura': ('django.db.models.fields.CharField', [], {'max_length': '60'}),
            'tensionarterial': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'ultimaVisitaMedica': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'uxiliaresBucales': ('django.db.models.fields.CharField', [], {'max_length': '2'})
        },
        'ActividadesClinicas.listadediagnosticos': {
            'Meta': {'object_name': 'ListadeDiagnosticos'},
            'codigoDiagnostico': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'nombreDiagnostico': ('django.db.models.fields.CharField', [], {'max_length': '30'})
        },
        'ActividadesClinicas.odontograma': {
            'Meta': {'object_name': 'Odontograma'},
            'doctor': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['altas.Medico']"}),
            'fechayHora': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'nombrePiezaDental': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'notas': ('django.db.models.fields.TextField', [], {}),
            'paciente': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['altas.Paciente']"}),
            'problemaDental': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['ActividadesClinicas.ListadeDiagnosticos']"})
        },
        'altas.medico': {
            'Ciudad': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'Meta': {'object_name': 'Medico'},
            'apellidoMaterno': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'apellidoPaterno': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'cedulaEstatal': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'codigoPostal': ('django.db.models.fields.IntegerField', [], {'max_length': '5'}),
            'correoElectronico': ('django.db.models.fields.EmailField', [], {'max_length': '50'}),
            'direccion': ('django.db.models.fields.CharField', [], {'max_length': '70'}),
            'especialidad': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'estado': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'licenciaDeEspecialidad': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'licenciaMedica': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'nombre': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'nombreUsuario': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'rfc': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'telefono': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'universidadEgreso': ('django.db.models.fields.CharField', [], {'max_length': '70'})
        },
        'altas.paciente': {
            'Meta': {'object_name': 'Paciente'},
            'apellidoMaterno': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'apellidoPaterno': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'ciudad': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'codigoPostal': ('django.db.models.fields.IntegerField', [], {'max_length': '5'}),
            'correoElectronico': ('django.db.models.fields.EmailField', [], {'max_length': '60'}),
            'credencialPaciente': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'direccion': ('django.db.models.fields.CharField', [], {'max_length': '70'}),
            'estado': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'grupo': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['precios.GrupoPrecios']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'nSs': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'nombre': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'sexo': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'telefono': ('django.db.models.fields.CharField', [], {'max_length': '20'})
        },
        'precios.grupoprecios': {
            'Meta': {'object_name': 'GrupoPrecios'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'nombreDelGrupo': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '50'})
        }
    }

    complete_apps = ['ActividadesClinicas']